services:
  bot:
    build: ../app
    image: tb-app:latest
    command: ["python","/app/bot.py"]
    env_file:
      - ../.env
    environment:
      STRAT_PROFILE: "blended_1000_trendonly"
      EXCHANGE: "binanceus"
      SYMBOL: "BTC/USDT"
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
    volumes:
      - /srv/trading-bots/data:/data
    restart: unless-stopped

  ui:
    build: ../app
    image: tb-app:latest
    command: ["bash","-lc","uvicorn ui:app --host 0.0.0.0 --port 8080"]
    environment:
      DATA_DIR: "/data"
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
      HOST_APP: "/host_app"
      HOST_COMPOSE: "/host_compose"
      HOST_GITHUB: "/host_github"
    volumes:
      - /srv/trading-bots/data:/data
      - /srv/trading-bots/app:/host_app:ro
      - /srv/trading-bots/compose:/host_compose:ro
      - /srv/trading-bots/.github:/host_github:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
