services:
  bot:
    build: ../app
    image: tb-app:latest
    container_name: tb-bot
    command: ["python","/app/bot.py"]
    env_file:
      - ../.env
    environment:
      EXCHANGE: "binanceus"
      SYMBOL: "BTC/USD"     # if you see InvalidSymbol, try "BTC/USD"
      TIMEFRAME: "5m"
      FAST: "7"
      SLOW: "25"
      ORDER_SIZE_USD: "50"
      START_CASH_USD: "10000"
      START_COIN_UNITS: "0"
      FEE_RATE: "0.001"
      CONFIRM_BARS: "2"
      MIN_HOLD_BARS: "3"
      THRESHOLD_PCT: "0.0005"
      MIN_TRADE_USD: "20"
      START_CASH_USD: "10000"
      START_COIN_UNITS: "0"
      FEE_RATE: "0.001"
      LOOP_SECONDS: "20"
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
    volumes:
      - /srv/trading-bots/data:/data
    restart: unless-stopped

  ui:
    build: ../app
    image: tb-app:latest
    container_name: tb-ui
    command: ["bash","-lc","uvicorn ui:app --host 0.0.0.0 --port 8080"]
    environment:
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
    volumes:
      - /srv/trading-bots/data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped
