services:
  bot:
    build: ../app
    image: tb-app:latest
    command: ["python","/app/bot.py"]
    env_file:
      - ../.env
    environment:
      EXCHANGE: "binanceus"
      SYMBOL: "BTC/USDT"
      TIMEFRAME: "1m"
      FAST: "7"
      SLOW: "25"
      # --- sizing via % of equity ---
      ORDER_PCT_EQUITY: "0.08"
      ORDER_SIZE_USD: "0"
      START_CASH_USD: "200"
      START_COIN_UNITS: "0"
      FEE_RATE: "0.001"
      # --- discipline & hysteresis ---
      CONFIRM_BARS: "1"
      MIN_HOLD_BARS: "2"
      THRESHOLD_PCT: "0.0005"
      MIN_TRADE_USD: "5"
      LOOP_SECONDS: "20"
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
    volumes:
      - /srv/trading-bots/data:/data
    restart: unless-stopped

  ui:
    build: ../app
    image: tb-app:latest
    command: ["bash","-lc","uvicorn ui:app --host 0.0.0.0 --port 8080"]
    environment:
      DATA_DIR: "/data"
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
      HOST_APP: "/host_app"
      HOST_COMPOSE: "/host_compose"
      HOST_GITHUB: "/host_github"
    volumes:
      - /srv/trading-bots/data:/data
      - /srv/trading-bots/app:/host_app:ro
      - /srv/trading-bots/compose:/host_compose:ro
      - /srv/trading-bots/.github:/host_github:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
