services:
  bot:
    build: ../app
    image: tb-app:latest
    container_name: tb-bot
    command: ["python","/app/bot.py"]
    env_file:
      - ../.env
    environment:
      EXCHANGE: "binanceus"
      SYMBOL: "BTC/USDT"     # if you see InvalidSymbol, try "BTC/USD"
      TIMEFRAME: "1m"
      FAST: "7"
      SLOW: "25"
      ORDER_SIZE_USD: "100"
      LOOP_SECONDS: "20"
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
    volumes:
      - /srv/trading-bots/data:/data
    restart: unless-stopped

  ui:
    build: ../app
    image: tb-app:latest
    container_name: tb-ui
    command: ["bash","-lc","uvicorn ui:app --host 0.0.0.0 --port 8080"]
    environment:
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
    volumes:
      - /srv/trading-bots/data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped
