services:
  bot:
    build: ../app
    image: tb-app:latest
    container_name: tb-bot
    command: ["python","/app/bot.py"]   # stays as-is unless you switched to bot_main.py
    env_file:
      - ../.env
    environment:
      EXCHANGE: "binanceus"
      SYMBOL: "BTC/USDT"       # or "BTC/USD" on Binance.US
      TIMEFRAME: "1m"
      FAST: "7"
      SLOW: "25"
      ORDER_SIZE_USD: "20"
      START_CASH_USD: "200"
      START_COIN_UNITS: "0"
      FEE_RATE: "0.001"
      CONFIRM_BARS: "2"
      MIN_HOLD_BARS: "3"
      THRESHOLD_PCT: "0.0003"
      MIN_TRADE_USD: "10"
      LOOP_SECONDS: "20"
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
    volumes:
      - /srv/trading-bots/data:/data
    restart: unless-stopped

  ui:
    build: ../app
    image: tb-app:latest
    container_name: tb-ui
    command: ["bash","-lc","uvicorn ui:app --host 0.0.0.0 --port 8080"]
    environment:
      DATA_DIR: "/data"
      STATE_PATH: "/data/paper_state.json"
      TRADES_PATH: "/data/paper_trades.json"
      HOST_APP: "/host_app"
      HOST_COMPOSE: "/host_compose"
      HOST_GITHUB: "/host_github"
    volumes:
      - /srv/trading-bots/data:/data:ro
      - /srv/trading-bots/app:/host_app:ro
      - /srv/trading-bots/compose:/host_compose:ro
      - /srv/trading-bots/.github:/host_github:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
