name: Deploy to Droplet
on:
  push:
    tags:
      - "deploy-*"
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref to deploy (tag or SHA)"
        required: false
concurrency:
  group: deploy-prod
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # For tag pushes, GitHub checks out the tag automatically.
        # For manual dispatch, pass a ref input if you want.
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Build docker image (smoke)
        run: docker build -t tb-app:latest app

      - name: Ship to droplet and restart (compose up)
        env:
          TB_HOST: ${{ secrets.TB_HOST }}
          TB_PW:   ${{ secrets.TB_PW }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y sshpass
          sshpass -p "$TB_PW" ssh -o StrictHostKeyChecking=no "$TB_HOST" "bash -s" <<'SH'
          set -euo pipefail
          cd /srv/trading-bots
          if [ ! -d .git ]; then
            git init
            git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          fi
          git fetch --all --tags --prune
          # checkout the exact ref this job is running on (tag for tag-push)
          REF="${GITHUB_REF_NAME:-main}"
          git checkout -f "$REF"
          docker compose -p tb -f compose/docker-compose.yml up -d --build --remove-orphans
          SH
