name: Deploy to Droplet
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package repo (git archive)
        run: git archive --format=tar.gz -o package.tgz HEAD

      - name: Upload package
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TB_HOST }}
          username: ${{ secrets.TB_USER }}
          password: ${{ secrets.TB_PASS }}
          source: "package.tgz"
          target: "/srv/trading-bots-repo"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TB_HOST }}
          username: ${{ secrets.TB_USER }}
          password: ${{ secrets.TB_PASS }}
          script: |
            set -e
            mkdir -p /srv/trading-bots /srv/trading-bots-repo
            cd /srv/trading-bots-repo
            tar -xzf package.tgz && rm -f package.tgz

            # sync repo -> live (keep data/logs/.env and ignore diag)
            rsync -a --delete --delete-delay --force \
              --exclude data --exclude logs --exclude .env --exclude _diag/ \
              /srv/trading-bots-repo/ /srv/trading-bots/

            # write .env AFTER rsync so --delete won't remove it
            : > /srv/trading-bots/.env
            printf "BINANCE_API_KEY=%s\n" "${{ secrets.BINANCE_API_KEY }}"   >> /srv/trading-bots/.env
            printf "BINANCE_API_SECRET=%s\n" "${{ secrets.BINANCE_API_SECRET }}" >> /srv/trading-bots/.env
            echo "GIT_BRANCH=${GITHUB_REF_NAME}" >> /srv/trading-bots/.env
            echo "DEPLOY_TAG=${GITHUB_REF##*/}"   >> /srv/trading-bots/.env
            echo "GIT_SHA=${GITHUB_SHA::7}"       >> /srv/trading-bots/.env

            # rebuild & restart
            docker compose -p tb -f /srv/trading-bots/compose/docker-compose.yml down --remove-orphans 
            docker compose -p tb -f /srv/trading-bots/compose/docker-compose.yml up -d --build --remove-orphans
