name: Deploy to Droplet
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package repo (git archive)
        run: git archive --format=tar.gz -o package.tgz HEAD

      - name: Upload package
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TB_HOST }}
          username: ${{ secrets.TB_USER }}
          password: ${{ secrets.TB_PASS }}
          source: "package.tgz"
          target: "/srv/trading-bots-repo"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TB_HOST }}
          username: ${{ secrets.TB_USER }}
          password: ${{ secrets.TB_PASS }}
          script: |
            set -e
            mkdir -p /srv/trading-bots /srv/trading-bots-repo
            cd /srv/trading-bots-repo
            tar -xzf package.tgz && rm -f package.tgz

            # write .env from GitHub Secrets (no heredoc; avoids YAML issues)
            : > /srv/trading-bots/.env
            printf "BINANCE_API_KEY=%s\n" "${{ secrets.BINANCE_API_KEY }}"   >> /srv/trading-bots/.env
            printf "BINANCE_API_SECRET=%s\n" "${{ secrets.BINANCE_API_SECRET }}" >> /srv/trading-bots/.env

            # sync to live dir (keep data/logs)
            rsync -a --delete --exclude data --exclude logs /srv/trading-bots-repo/ /srv/trading-bots/

            # rebuild & restart
            docker compose -f /srv/trading-bots/compose/docker-compose.yml up -d --build
