name: Deploy to Droplet
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TB_HOST }}
          username: ${{ secrets.TB_USER }}
          password: ${{ secrets.TB_PASS }}
          script: |
            set -e
            sudo apt-get update -y && sudo apt-get install -y git rsync docker.io || true
            CLONE_DIR=/srv/trading-bots-repo
            APP_DIR=/srv/trading-bots
            if [ ! -d "$CLONE_DIR/.git" ]; then
              rm -rf "$CLONE_DIR"
              git clone https://github.com/${{ github.repository }} "$CLONE_DIR"
            else
              git -C "$CLONE_DIR" fetch --all
              git -C "$CLONE_DIR" reset --hard origin/main
            fi
            rsync -a --delete --exclude data --exclude logs "$CLONE_DIR"/ "$APP_DIR"/
            docker compose -f "$APP_DIR/compose/docker-compose.yml" up -d --build
