name: Mirror to Public

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ 'deploy-*' ]

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure git identity
        run: |
          git config user.name  "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

      - name: Configure HTTP auth header (PAT)
        env:
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          git config --global --unset-all http.https://api.github.com/.extraheader || true
          header=$(printf "x-access-token:%s" "${MIRROR_PAT}" | base64 -w0 2>/dev/null || printf "x-access-token:%s" "${MIRROR_PAT}" | base64)
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic ${header}"
          git config --global http.https://api.github.com/.extraheader "AUTHORIZATION: basic ${header}"

      - name: Mirror main → main
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          MIRROR_REPO: ${{ secrets.MIRROR_REPO }}
        run: |
          git push "https://github.com/${MIRROR_REPO}.git" HEAD:refs/heads/main --force

      - name: Mirror deploy tag
        if: ${{ startsWith(github.ref, 'refs/tags/deploy-') }}
        env:
          MIRROR_REPO: ${{ secrets.MIRROR_REPO }}
        run: |
          git push "https://github.com/${MIRROR_REPO}.git" "${GITHUB_REF}:${GITHUB_REF}" --force
