name: Mirror to Public
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Push to public mirror
        run: |
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"
          git push --force --prune https://${{ secrets.MIRROR_TOKEN }}@github.com/${{ github.repository_owner }}/trading-bot-public.git HEAD:main
