name: Mirror to Public

on:
  push:
    branches: [ main ]
    tags:
      - 'deploy-*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sanity: ensure secrets exist
        run: |
          test -n "${{ secrets.MIRROR_PAT }}" || { echo "MIRROR_PAT missing"; exit 1; }
          test -n "${{ secrets.MIRROR_REPO }}" || { echo "MIRROR_REPO missing"; exit 1; }

      - name: Add public remote
        run: |
          git remote add public https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/${{ secrets.MIRROR_REPO }}.git
          git remote -v

      - name: Mirror main → main
        if: github.ref == 'refs/heads/main'
        run: |
          git push public refs/heads/main:refs/heads/main --force-with-lease

      - name: Mirror deploy tag
        if: startsWith(github.ref, 'refs/tags/deploy-')
        run: |
          git push public $GITHUB_REF:$GITHUB_REF --force-with-lease
