name: Mirror Auth Test

on:
  workflow_dispatch:
    inputs:
      write_test:
        description: "Also test write access by pushing a temp branch (creates & deletes _mirror_write_test)"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify required secrets
        env:
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
          MIRROR_REPO: ${{ secrets.MIRROR_REPO }}
        run: |
          if [ -z "${MIRROR_PAT}" ]; then
            echo "MIRROR_PAT missing"; exit 1
          fi
          if [ -z "${MIRROR_REPO}" ]; then
            echo "MIRROR_REPO missing"; exit 1
          fi

      - name: Configure git identity
        run: |
          git config user.name  "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

      - name: Read probe using PAT URL
        env:
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
          MIRROR_REPO: ${{ secrets.MIRROR_REPO }}
        run: |
          echo "Listing heads from public (should succeed):"
          git ls-remote --heads "https://x-access-token:${MIRROR_PAT}@github.com/${MIRROR_REPO}.git"

      - name: Write probe create temp branch
        if: ${{ inputs.write_test }}
        env:
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
          MIRROR_REPO: ${{ secrets.MIRROR_REPO }}
        run: |
          echo "Pushing temp branch to test write access..."
          git push "https://x-access-token:${MIRROR_PAT}@github.com/${MIRROR_REPO}.git" HEAD:refs/heads/_mirror_write_test --force

      - name: Write probe delete temp branch
        if: ${{ inputs.write_test }}
        env:
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
          MIRROR_REPO: ${{ secrets.MIRROR_REPO }}
        run: |
          echo "Deleting temp branch..."
          git push "https://x-access-token:${MIRROR_PAT}@github.com/${MIRROR_REPO}.git" :refs/heads/_mirror_write_test
