name: Rollback
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Deploy tag to redeploy (deploy-YYYYMMDD-HHMM-<sha>)"
        required: true
concurrency:
  group: deploy-prod
  cancel-in-progress: true
jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { ref: ${{ inputs.tag }} }
      - name: Redeploy tag
        env:
          TB_HOST: ${{ secrets.TB_HOST }}
          TB_PW:   ${{ secrets.TB_PW }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y sshpass
          sshpass -p "$TB_PW" ssh -o StrictHostKeyChecking=no "$TB_HOST" "bash -s" <<'SH'
          set -euo pipefail
          cd /srv/trading-bots
          git fetch --all --tags --prune
          git checkout -f "${ROLLBACK_TAG}"
          docker compose -p tb -f compose/docker-compose.yml up -d --build --remove-orphans
          SH
        env:
          ROLLBACK_TAG: ${{ inputs.tag }}
